threads:
  - thread_name: "Axcpt_baseline"
    log_file: "Axcpt_baseline.log"
    scripts:
      - "3dDeconvolve.sh"
      - "3dREMLFit.sh"
      - "roistats.sh"
  - thread_name: "Axcpt_reactive"
    log_file: "Axcpt_reactive.log"
    scripts:
      - "3dDeconvolve.sh"
      - "3dREMLFit.sh"
      - "roistats.sh"
  - thread_name: "Axcpt_baseline"
    log_file: "Axcpt_baseline.log"
    scripts:
      - "3dDeconvolve3.sh"
      - "3dREMLFit3.sh"
      - "roistats3.sh"
  - thread_name: "Axcpt_reactive"
    log_file: "Axcpt_reactive.log"
    scripts:
      - "3dDeconvolve3.sh"
      - "3dREMLFit3.sh"
      - "roistats3.sh"